Arrays Mathematics

Basic mathematical functions operate element-wise on arrays. They are availabe both as operator overloads and as functions in the NumPy module.

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4], float)
b = np.array([5, 6, 7, 8], float)

print(a+b)
print(np.add(a, b))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]


In [2]:
print(a-b)
print(np.subtract(a, b))

[-4. -4. -4. -4.]
[-4. -4. -4. -4.]


In [3]:
print(a * b)
print(np.multiply(a, b))

[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]


In [4]:
print(a / b)
print(np.divide(a, b))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
print (a % b)
print (np.mod(a, b))

[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [7]:
print(a ** b)
print(np.power(a, b))

[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [22]:
import numpy as np
N, M  = map(int, input().split())

A = [list(map(int, input().split())) for _ in range(N)]

B = [list(map(int, input().split())) for _ in range(N)]


print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.floor_divide(A, B))
print(np.mod(A, B))
print(np.power(A, B))

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
