Concatenate

Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined.

In [10]:
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.array([7, 8, 9])

result = np.concatenate((array_1, array_2, array_3))
print(result)

[1 2 3 4 5 6 7 8 9]


If an array has more than one dimension, it is possible to specify the axis alogn which multiple arrays are concatenated. By default, it is along the first dimension.

In [17]:
array_1 = np.array([[1, 2, 3], [0, 0, 0]])
array_2 = np.array([[0, 0, 0], [7, 8, 9]])

result = np.concatenate((array_1, array_2), axis=1)
print(result)
result = np.concatenate((array_1, array_2), axis=0)
print(result)

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


Task

You are given two integer arrays of size N x P and M x P (N & M are rows, and P is the column).
Your task is to concatenate the arrays along axis 0.

 - Input Format:
    - The first line contains space separeted integers N, M and P.
    - The next N lines contains the space separated elements of the P columns.
    - After that, the next M lines contains the space separeted elements of the P columns.
 
 - Output Format:
    - Print the concatenated array of size (N + M)x P

In [20]:
N, M, P = map(int, input().split())

elements_of_P_N = [list(map(int, input().split())) for _ in range(N)]

elements_of_P_M = [list(map(int, input().split())) for _ in range(M)]

elements_of_P_N = np.array(elements_of_P_N)
elements_of_P_M = np.array(elements_of_P_M)

arr = np.concatenate((elements_of_P_N, elements_of_P_M), axis=0)
print(arr)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
