Floor, Ceil and Hint

- Floor: The tool floor returns the floor of the input element-wise. The floor of x is the largest integer i where i <= x.

In [1]:
import numpy as np

my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.floor(my_array))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


- Ceil: The tool ceil returns ceiling of the input element-wise. The ceiling of x is the smaller integer i where i >= x.

In [2]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.ceil(my_array))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


 - Rint: The rint tool rounds to the nearest integer of input element-wise.

In [3]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.rint(my_array))

[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


- Task: You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.
- Note: In order to get the correct output format, add the line np.set_printoptions(legacy='1.13') below the numpy import.
    - Input Format: A single line of input containing the space separated elements of array A.
    - Output Format: On the first line, print floor of A. On the second line, print the ceil of A. On the third line, print the rint of A.

In [6]:
np.set_printoptions(legacy='1.13')

my_array = list(map(float, input().split()))
print(np.floor(my_array))
print(np.ceil(my_array))
print(np.rint(my_array))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
