Identity

- The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as 1 and the rest as 0. The default type of element is float.

In [1]:
import numpy as np

print(np.identity(3)) # 3 is for dimension 3 x 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Eye: The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter k. A positive k is for upper diagonal, a negative k is for the lower, and a 0 k (default) is for the diagonal.

In [2]:
print(np.eye(8, 7, k = 1)) # 8 x 7 Dimensional array with first upper diagonal 1.

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [3]:
print(np.eye(8, 7, k = -2))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


- Task: Your task is to print an array of size N x M with its main diagonal elements as 1's and 0's everywhere else.
    - Note: In order to get alignment correct, please insert the line np.set_printoptions(legac='1.13') below the numpy import.
        - Input Format: A single line containing the space separated values of N and M
            - N denotes de rows
            - M denotes de columns
        - Output Format: Print the desired N x M array.


In [8]:
np.set_printoptions(legacy='1.13')
N, M = map(int, input().split())

print(np.eye(N, M, k = 0))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
