Shape and Reshape

- Shape : The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array

In [1]:
import numpy as np

my__1D_array = np.array([1, 2, 3, 4, 5])
print (my__1D_array.shape) # (5, ) -> 1 row and 5 columns

my__2D_array = np.array([[1, 2], [3, 4], [6, 5]])
print (my__2D_array.shape) # (3, 2) -> 3 rows and 2 columns


(5,)
(3, 2)


In [2]:
# Using shape to change array dimensions

change_array = np.array([1, 2, 3, 4, 5, 6])
change_array.shape = (3,2)
print (change_array)

[[1 2]
 [3 4]
 [5 6]]


- Reshape: The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

In [4]:
my_array = np.array([1, 2, 3, 4, 5, 6])
print(np.reshape(my_array, (3, 2)))
print (my_array)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


- Task: You are given a space separeted list of nine integers. Your task is to convert this list to into a 3X3 NumPy array.

    - Input Format: A single line of output containing 9 space separeted intergers
    - Output Format: Print the 3X3 NumPy array.

        - Sample Input : 1 2 3 4 5 6 7 8 9
        - Sample Output : [[1 2 3]
                            [4 5 6]
                                [7 8 9]]

In [21]:
def shape_my_array(arr):
    arr = np.array(arr, dtype=int)
    arr.shape = (3, 3)
    return arr

arr = input().strip().split(' ')
result = shape_my_array(arr)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
