Transpose and Flatten

 - Transpose: We can generate the transposition of an array using tool numpy.transpose.
 It will not affect the original array, but it will create a new array.

In [1]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print (np.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


- Flatten: The tool flatten creates a copy of the input array flattened to one dimension.

In [2]:
my_array = np.array([[1,2,3],
                    [4,5,6]])
print (my_array.flatten())

[1 2 3 4 5 6]


- Task: You are given a NxM integer array matrix with space separeted elements (N=rows and M = columns).
Your task is to print the transpose and flatten results.
    - Input format: The first line contains the space separated values of N and M. The next N lines contains the space separeted elements of M columns.
    - Output format: First, print the transpose array and the print the flatten.
    
        - Sample input:  2 2
                         1 2
                         3 4
        - Sample output
                        [[1 3]
                         [2 4]]
                         [1 2 3 4]
                         

In [16]:
def arr_transpose(arr, N, M):
    arr = np.array(arr, dtype=int)
    arr.shape = (N, M)
    print(np.transpose(arr))
    print("\n")
    print(arr.flatten())


In [ ]:
# Leitura das dimensões
# Lê a primeira linha da entrada, que tem dois números: N(número de linhas) e M (número de colunas).
# input().split() separa os números por espaço
# map(int, ...)converte esses números para int.
# O resultado é desempacotado em N e M.
N, M = map(int, input().split())

# Leitura dos dados e criação do array
# Lê as próximas N linhas, onde cada linha tem m números.
# input().split() divide os números da linha
# map(int, ...) converte os números de string para inteiro
# list(...) transforma o resultado em uma lista de inteiros
result = [list(map(int, input().split()))for _ in range(N)]
arr = np.array(result)

# Transposta
print(np.transpose(arr))
# print(arr.T)

# Flatten

print(arr.flatten())    


[[1 3]
 [2 4]]
[1 2 3 4]
