Transpose and Flatten

 - Transpose: We can generate the transposition of an array using tool numpy.transpose.
 It will not affect the original array, but it will create a new array.

In [ ]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print (np.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


- Flatten: The tool flatten creates a copy of the input array flattened to one dimension.

In [2]:
my_array = np.array([[1,2,3],
                    [4,5,6]])
print (my_array.flatten())

[1 2 3 4 5 6]


- Task: You are given a NxM integer array matrix with space separeted elements (N=rows and M = columns).
Your task is to print the transpose and flatten results.
    - Input format: The first line contains the space separated values of N and M. The next N lines contains the space separeted elements of M columns.
    - Output format: First, print the transpose array and the print the flatten.
    
        - Sample input: 2 2
                        1 2
                        3 4
        - Sample output
                        [[1 3]
                         [2 4]]
                         [1 2 3 4]
                         