Zeros and Ones

- Zeros: The zeros tool returns a new array with a given shape and type filled with 0's.

In [6]:
import numpy as np

print (np.zeros((1, 2))) # Default type is float
# Output : [[0. 0.]]

print(np.zeros((1, 2), dtype= np.int_)) # Type changes to int
# Output : [[0 0]]

[[0. 0.]]
[[0 0]]


- Ones: The ones tool returns a new array with a given shape and type filled with 1's.

In [7]:
print(np.ones((1, 2)))  # Default type is float
# Output : [[1. 1.]]

print(np.ones((1, 2), dtype=np.int_)) # Type changes to int
# Output : [[1 1]]

[[1. 1.]]
[[1 1]]


- Task: You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions. Your task is to print an array of the given shape and integer type using the tools np.zeros and np.ones.
    
    - Input Format: A single line containing the space-separated integers.
    - Constraints: 1 <= each integer <=3.
    - Output Format: First, print the array using np.zeros tool and then print the array with the np.ones tool.


In [ ]:
shape = tuple(map(int, input().split()))

zeros = np.zeros(shape, dtype=int)
print(zeros)

ones = np.ones(shape, dtype=int)
print(ones)

In [ ]:
shape = map(int, input().split())

print(np.zeros((shape), dtype=int))
    #print('\n')

print(np.ones((shape), dtype=int))
    #print('\n')


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
